### ISSUE TITLE
Cargo build failed 

### ISSUE THREAD

**Issue by dolphin22** [arashsm79/OFMon#3]
I am new to Rust and tried to build a firmware to test on my ESP32 but failed with error message, please help to redirect me to a potential fix. Please let me know if more info is needed. I successfully built a sample std project from https://esp-rs.github.io/book/writing-your-own-application/generate-project/index.html. Thanks!

>cargo 1.71.0-nightly (cfd3bbd8f 2023-06-08)

> rustup 1.26.0 (5af9b9484 2023-04-05)
>info: This is the version for the rustup toolchain manager, not the rustc compiler.
>info: The currently active `rustc` version is `rustc 1.71.0-nightly (4ca000ac8 2023-07-13) (1.71.0.1)`

>espup 0.5.0

>    Compiling esp-idf-sys v0.31.12
>   Compiling embedded-svc v0.22.3
> error: lifetime may not live long enough
>   --> /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/embedded-svc->0.22.3/src/utils/asynch/signal.rs:289:13
>   |
>274 |       impl<'s, S, T> Receiver for SignalChannel<'s, S, T>
>    |            -- lifetime `'s` defined here
>...
>288 |           fn recv(&mut self) -> Self::RecvFuture<'_> {
 >   |                   - let's call the lifetime of this reference `'1`
>289 | /             async move {
>290 | |                 let value = futures::future::poll_fn(move |cx| self.0...
>291 | |
>292 | |                 value
>293 | |             }
>    | |_____________^ method was supposed to return data with lifetime `'s` but it is returning data with lifetime `'1`

>error: could not compile `embedded-svc` (lib) due to previous error
>warning: build failed, waiting for other jobs to finish...
>error: failed to run custom build command for `esp-idf-sys v0.31.12`

**Comment by arashsm79** [comment]
The platform for ESP on rust is not yet stable and is under active development. You would have to consult the new version of docs and changelogs to find what has changed.
